version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mysteryverse-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mysteryverse-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mysteryverse
      - JWT_SECRET=supersecretjwtkeyforlocaldevelopmentonly
    depends_on:
      - mongo

volumes:
  mongo_data:
